import { MatchdayDatabase } from './types.ts';

export const initialDatabase: MatchdayDatabase = {
  adminPin: '1880', // Legacy fallback
  staffCode: 'AGF1880',
  adminCode: 'AGF176',
  sessions: [],
  mobilePayNumber: '1880',
  visits: 142,
  activeMatchdayId: 'matchday-1',
  matchdays: [
    {
      id: 'matchday-1',
      title: 'AGF Matchday – Dobbeltbrag i Ceres Arena',
      date: 'Lørdag d. 10. oktober 2026',
      venue: 'Ceres Arena',
      active: true,
      featuredHero: {
        enabled: true,
        badge: 'PAUSETILBUD',
        title: 'DAGENS PAUSETILBUD',
        subtitle: '2 fadøl for 80 kr. i arenaens kiosker',
        actionText: 'SE TILBUD',
        actionTarget: 'tilbud',
      },
      looadUrl: 'https://looad.dk/pages/klub-agf-haandbold',
      looadTitle: 'STØT AGF HÅNDBOLD MED LOOAD',
      looadDescription: 'Skift elselskab til Looad og støt samtidig AGF Håndbold.',
      welcomeMessage: 'Velkommen til AGF Håndbold i Ceres Arena. Støt de hvide!',
      mobilePayNumber: '1880',
      createdAt: new Date().toISOString(),
    },
    {
      id: 'matchday-2',
      title: 'AGF Håndbold – Lokalderby mod Skanderborg',
      date: 'Søndag d. 25. oktober 2026',
      venue: 'Ceres Arena',
      active: false,
      featuredHero: {
        enabled: true,
        badge: 'KOMMENDE',
        title: 'VELKOMMEN TIL DERBY',
        subtitle: 'Dørene åbner kl. 13:00 til sæsonens største lokalopgør',
        actionText: 'SE PROGRAMMET',
        actionTarget: 'program',
      },
      looadUrl: 'https://looad.dk/pages/klub-agf-haandbold',
      looadTitle: 'STØT AGF HÅNDBOLD MED LOOAD',
      looadDescription: 'Skift elselskab til Looad og støt samtidig AGF Håndbold.',
      welcomeMessage: 'Gør dig klar til det store lokalopgør!',
      mobilePayNumber: '1880',
      createdAt: new Date().toISOString(),
    }
  ],
  matches: [
    {
      id: 'match-1',
      matchdayId: 'matchday-1',
      category: 'DAMER',
      league: '1. Division Damer',
      homeTeam: 'AGF Håndbold',
      awayTeam: 'Silkeborg-Voel',
      time: '13:00',
      venue: 'Ceres Arena',
      status: 'upcoming',
      liveMatchUrl: 'https://tophaandbold.dk',
    },
    {
      id: 'match-2',
      matchdayId: 'matchday-1',
      category: 'HERRER',
      league: '1. Division Herrer',
      homeTeam: 'AGF Håndbold',
      awayTeam: 'Skanderborg AGF',
      time: '15:15',
      venue: 'Ceres Arena',
      status: 'upcoming',
      liveMatchUrl: 'https://tophaandbold.dk',
    }
  ],
  schedule: [
    {
      id: 'sched-1',
      matchdayId: 'matchday-1',
      time: '11:45',
      title: 'Dørene åbner & Fanzonen starter',
      description: 'Kiosken tænder grillen, og der er musik samt opvarmningsaktiviteter i hallen.',
      location: 'Ceres Arena - Fanzone & Hal 1',
      icon: 'door-open',
      status: 'completed',
      order: 1,
    },
    {
      id: 'sched-2',
      matchdayId: 'matchday-1',
      time: '12:45',
      title: 'AGF Damer vs. Horsens HK',
      description: '1. Division Damer. Støt pigerne i jagten på to vigtige point!',
      location: 'Bane 1',
      icon: 'trophy',
      status: 'live',
      order: 2,
    },
    {
      id: 'sched-3',
      matchdayId: 'matchday-1',
      time: '14:20',
      title: 'Pauseaktivitet: Skudmåler & Konkurrencer',
      description: 'Test dit skud på vores radar i fanzonen og dyst mod vennerne.',
      location: 'Fanzonen bag sektion B',
      icon: 'target',
      status: 'upcoming',
      order: 3,
    },
    {
      id: 'sched-4',
      matchdayId: 'matchday-1',
      time: '15:15',
      title: 'AGF Herrer vs. Skanderborg AGF',
      description: 'Det store lokalopgør! Fuld tænding på lægterne.',
      location: 'Bane 1',
      icon: 'swords',
      status: 'upcoming',
      order: 4,
    },
    {
      id: 'sched-5',
      matchdayId: 'matchday-1',
      time: '17:00',
      title: 'Kåring af Kampens Spiller & Aftermatch',
      description: 'Præmieoverrækkelse præsenteret af Arbejdernes Landsbank.',
      location: 'Midtercirklen',
      icon: 'award',
      status: 'upcoming',
      order: 5,
    }
  ],
  products: [
    {
      id: 'prod-1',
      name: 'Fadøl (Royal Pilsner / Classic 0,5L)',
      category: 'Fadøl',
      price: 45,
      available: true,
      promotionalLabel: 'Favorit',
      description: 'Frisktappet kold fadøl fra Ceres.',
    },
    {
      id: 'prod-2',
      name: 'Pausepakke (2 store Fadøl)',
      category: 'Fadøl',
      price: 80,
      available: true,
      promotionalLabel: 'Spar 10 kr',
      description: 'Tag en ven med i baren og spar penge.',
    },
    {
      id: 'prod-3',
      name: 'Faxe Kondi / Pepsi Max (0,5L)',
      category: 'Sodavand',
      price: 25,
      available: true,
      promotionalLabel: '',
      description: 'Iskold sodavand.',
    },
    {
      id: 'prod-4',
      name: 'Kildevand (0,5L)',
      category: 'Vand',
      price: 20,
      available: true,
      promotionalLabel: '',
      description: 'Naturligt mineralvand.',
    },
    {
      id: 'prod-5',
      name: 'Filterkaffe (Friskbrygget)',
      category: 'Kaffe',
      price: 20,
      available: true,
      promotionalLabel: '',
      description: 'Varm sort kaffe fra baren.',
    },
    {
      id: 'prod-6',
      name: 'Varm Kakao m/ flødeskum',
      category: 'Kaffe',
      price: 25,
      available: true,
      promotionalLabel: '',
      description: 'Perfekt til de kolde dage.',
    },
    {
      id: 'prod-7',
      name: 'Fransk Hotdog',
      category: 'Mad',
      price: 35,
      available: true,
      promotionalLabel: 'Populær',
      description: 'Sprødt baguettebrød med klassisk fransk dressing.',
    },
    {
      id: 'prod-8',
      name: 'Toast m/ skinke og ost',
      category: 'Mad',
      price: 35,
      available: true,
      promotionalLabel: '',
      description: 'Lunt og nystegt toast.',
    },
    {
      id: 'prod-9',
      name: 'Pølsehorn',
      category: 'Mad',
      price: 25,
      available: true,
      promotionalLabel: '',
      description: 'Lækkert mellemmåltid til børn og voksne.',
    },
    {
      id: 'prod-10',
      name: 'Popcorn (Stor bøtte)',
      category: 'Snacks',
      price: 30,
      available: true,
      promotionalLabel: '',
      description: 'Varme, saltede popcorn.',
    },
    {
      id: 'prod-11',
      name: 'Saltede Peanuts',
      category: 'Snacks',
      price: 20,
      available: false, // Out of stock example
      promotionalLabel: '',
      description: 'Klassiske peanuts til øllen.',
    },
    {
      id: 'prod-12',
      name: 'Haribo pose (Matador Mix / Stjernemix)',
      category: 'Slik',
      price: 25,
      available: true,
      promotionalLabel: '',
      description: '120g blandet slik.',
    }
  ],
  coupons: [
    {
      id: 'coup-1',
      matchdayId: 'matchday-1',
      title: '🔥 PAUSETILBUD – 2 fadøl for 80 kr.',
      description: 'Køb 2 fadøl i pausen og spar 10 kr. Aktivér kuponen og vis den i kiosken inden for 10 minutter.',
      originalPrice: 90,
      offerPrice: 80,
      active: true,
      activationDurationMinutes: 10,
      maxRedemptions: 150,
      redemptionsCount: 38,
      sponsor: 'Ceres Bryggerierne',
    },
    {
      id: 'coup-2',
      matchdayId: 'matchday-1',
      title: '🌭 Matchday Menu: Fransk hotdog + Sodavand',
      description: 'Vælg en valgfri sodavand og en fransk hotdog for kun 50 kr. (normalpris 60 kr.).',
      originalPrice: 60,
      offerPrice: 50,
      active: true,
      activationDurationMinutes: 15,
      maxRedemptions: 100,
      redemptionsCount: 24,
      sponsor: 'Arbejdernes Landsbank',
    },
    {
      id: 'coup-3',
      matchdayId: 'matchday-1',
      title: '☕ Kaffe & Kage tilbud',
      description: 'Få en kop friskbrygget kaffe og et stykke chokoladekage for 30 kr.',
      originalPrice: 45,
      offerPrice: 30,
      active: true,
      activationDurationMinutes: 15,
      maxRedemptions: 80,
      redemptionsCount: 19,
      sponsor: 'Kiosken',
    }
  ],
  couponRedemptions: [],
  competitions: [
    {
      id: 'comp-1',
      name: 'Skudmåler',
      description: 'Hvem har kampens hårdeste skudarm? Mål dit håndboldskud i km/t på radaren i fanzonen.',
      scoringUnit: 'km/t',
      higherScoreWins: true,
      active: true,
      maxLeaderboardEntries: 5,
      sponsor: 'hummel',
    },
    {
      id: 'comp-2',
      name: 'Præcisionsskydning',
      description: 'Ram plet i målhjørnerne og saml flest mulige point på 3 forsøg.',
      scoringUnit: 'point',
      higherScoreWins: true,
      active: true,
      maxLeaderboardEntries: 5,
      sponsor: 'AGF Håndbold',
    },
    {
      id: 'comp-3',
      name: 'Crossbar Challenge',
      description: 'Hvor mange gange i træk kan du ramme overliggeren fra 7-meter stregen?',
      scoringUnit: 'træffere',
      higherScoreWins: true,
      active: true,
      maxLeaderboardEntries: 5,
      sponsor: 'Arbejdernes Landsbank',
    }
  ],
  scores: [
    // Skudmåler scores
    { id: 'score-1', competitionId: 'comp-1', matchdayId: 'matchday-1', participantName: 'Mikkel Lind', score: 96, timestamp: '12:15', isNewRecord: true },
    { id: 'score-2', competitionId: 'comp-1', matchdayId: 'matchday-1', participantName: 'Frederik B.', score: 92, timestamp: '12:20', isNewRecord: false },
    { id: 'score-3', competitionId: 'comp-1', matchdayId: 'matchday-1', participantName: 'Alma V.', score: 87, timestamp: '12:28', isNewRecord: false },
    { id: 'score-4', competitionId: 'comp-1', matchdayId: 'matchday-1', participantName: 'Oscar K.', score: 84, timestamp: '12:35', isNewRecord: false },
    { id: 'score-5', competitionId: 'comp-1', matchdayId: 'matchday-1', participantName: 'Laura Schmidt', score: 81, timestamp: '12:40', isNewRecord: false },
    
    // Præcisionsskydning scores
    { id: 'score-6', competitionId: 'comp-2', matchdayId: 'matchday-1', participantName: 'Jonas Dahl', score: 28, timestamp: '12:10', isNewRecord: true },
    { id: 'score-7', competitionId: 'comp-2', matchdayId: 'matchday-1', participantName: 'Sofie M.', score: 24, timestamp: '12:18', isNewRecord: false },
    { id: 'score-8', competitionId: 'comp-2', matchdayId: 'matchday-1', participantName: 'Rasmus P.', score: 20, timestamp: '12:25', isNewRecord: false },

    // Crossbar Challenge scores
    { id: 'score-9', competitionId: 'comp-3', matchdayId: 'matchday-1', participantName: 'Emil Thorn', score: 4, timestamp: '12:30', isNewRecord: true },
    { id: 'score-10', competitionId: 'comp-3', matchdayId: 'matchday-1', participantName: 'Mathias H.', score: 3, timestamp: '12:32', isNewRecord: false }
  ],
  votingSessions: [
    {
      id: 'vote-damer',
      matchdayId: 'matchday-1',
      category: 'DAMER',
      title: 'Kampens Spiller – Damer',
      status: 'open',
    },
    {
      id: 'vote-herrer',
      matchdayId: 'matchday-1',
      category: 'HERRER',
      title: 'Kampens Spiller – Herrer',
      status: 'not_started',
    }
  ],
  players: [
    // Damer - AGF Håndbold (HOME)
    { id: 'p-1', sessionId: 'vote-damer', name: 'Laura Nielsen', number: 1, position: 'Målvogter', team: 'HOME' },
    { id: 'p-2', sessionId: 'vote-damer', name: 'Sofie Møller', number: 7, position: 'Playmaker', team: 'HOME' },
    { id: 'p-3', sessionId: 'vote-damer', name: 'Emma Jensen', number: 10, position: 'Venstre Fløj', team: 'HOME' },
    { id: 'p-4', sessionId: 'vote-damer', name: 'Mathilde Holm', number: 14, position: 'Stregspiller', team: 'HOME' },
    { id: 'p-5', sessionId: 'vote-damer', name: 'Julie Kristensen', number: 22, position: 'Højre Back', team: 'HOME' },
    { id: 'p-6', sessionId: 'vote-damer', name: 'Amalie Winther', number: 18, position: 'Forsvar', team: 'HOME' },

    // Damer - Udehold (AWAY)
    { id: 'p-d-away-1', sessionId: 'vote-damer', name: 'Andrea West Bendtsen', number: 8, position: 'Venstre Back', team: 'AWAY' },
    { id: 'p-d-away-2', sessionId: 'vote-damer', name: 'Maja Munch Laursen', number: 12, position: 'Målvogter', team: 'AWAY' },
    { id: 'p-d-away-3', sessionId: 'vote-damer', name: 'Thea Rasmussen', number: 17, position: 'Playmaker', team: 'AWAY' },
    { id: 'p-d-away-4', sessionId: 'vote-damer', name: 'Karen Klokker', number: 24, position: 'Stregspiller', team: 'AWAY' },

    // Herrer - AGF Håndbold (HOME)
    { id: 'p-7', sessionId: 'vote-herrer', name: 'Mikkel Rasmussen', number: 1, position: 'Målvogter', team: 'HOME' },
    { id: 'p-8', sessionId: 'vote-herrer', name: 'Frederik Bruun', number: 4, position: 'Playmaker', team: 'HOME' },
    { id: 'p-9', sessionId: 'vote-herrer', name: 'Mads Svendsen', number: 9, position: 'Stregspiller', team: 'HOME' },
    { id: 'p-10', sessionId: 'vote-herrer', name: 'Christian Lind', number: 15, position: 'Venstre Back', team: 'HOME' },
    { id: 'p-11', sessionId: 'vote-herrer', name: 'Magnus Toft', number: 21, position: 'Højre Fløj', team: 'HOME' },
    { id: 'p-12', sessionId: 'vote-herrer', name: 'Kasper Broe', number: 11, position: 'Højre Back', team: 'HOME' },

    // Herrer - Udehold (AWAY)
    { id: 'p-h-away-1', sessionId: 'vote-herrer', name: 'Kristoffer Laursen', number: 1, position: 'Målvogter', team: 'AWAY' },
    { id: 'p-h-away-2', sessionId: 'vote-herrer', name: 'Morten Balling', number: 5, position: 'Venstre Fløj', team: 'AWAY' },
    { id: 'p-h-away-3', sessionId: 'vote-herrer', name: 'Lars Skaarup', number: 7, position: 'Højre Fløj', team: 'AWAY' },
    { id: 'p-h-away-4', sessionId: 'vote-herrer', name: 'Emil Lærke', number: 13, position: 'Venstre Back', team: 'AWAY' },
  ],
  votes: [
    { id: 'v-1', sessionId: 'vote-damer', playerId: 'p-2', deviceId: 'dev-seed-1', timestamp: '12:50' },
    { id: 'v-2', sessionId: 'vote-damer', playerId: 'p-2', deviceId: 'dev-seed-2', timestamp: '12:52' },
    { id: 'v-3', sessionId: 'vote-damer', playerId: 'p-1', deviceId: 'dev-seed-3', timestamp: '12:55' },
    { id: 'v-4', sessionId: 'vote-damer', playerId: 'p-4', deviceId: 'dev-seed-4', timestamp: '13:00' },
    { id: 'v-5', sessionId: 'vote-damer', playerId: 'p-2', deviceId: 'dev-seed-5', timestamp: '13:05' },
  ],
  partners: [
    // 1. HOVEDSPONSOR
    {
      id: 'part-raundahl-moesby',
      name: 'Raundahl & Moesby',
      companyName: 'Raundahl & Moesby',
      logo: '/partners/raundahl-moesby.png',
      logoUrl: '/partners/raundahl-moesby.png',
      category: 'HOVEDSPONSOR',
      sponsorCategory: 'HOVEDSPONSOR',
      websiteUrl: 'https://www.raundahl-moesby.dk',
      shortDescription: 'Stolt hovedsponsor for AGF Håndbold. Totalentreprenør med fokus på kvalitet og bæredygtighed.',
      message: 'Stolt hovedsponsor for AGF Håndbold. Totalentreprenør med fokus på kvalitet og bæredygtighed.',
      active: true,
      sortOrder: 1,
      featured: true,
    },
    // 2. AGF PLAY
    {
      id: 'part-sport-24',
      name: 'Sport 24',
      companyName: 'Sport 24',
      logo: '/partners/sport-24.png',
      logoUrl: '/partners/sport-24.png',
      category: 'AGF PLAY',
      sponsorCategory: 'AGF PLAY',
      websiteUrl: 'https://www.sport24.dk',
      shortDescription: 'Danmarks største sportsforretningskæde. Officiel sportspartner.',
      message: 'Danmarks største sportsforretningskæde. Officiel sportspartner.',
      active: true,
      sortOrder: 1,
      featured: false,
    },
    {
      id: 'part-jasa-company',
      name: 'Jasa Company',
      companyName: 'Jasa Company',
      logo: '/partners/jasa-company.png',
      logoUrl: '/partners/jasa-company.png',
      category: 'AGF PLAY',
      sponsorCategory: 'AGF PLAY',
      websiteUrl: 'https://www.jasa.dk',
      shortDescription: 'Professionelle beslag- og låseløsninger til byggeriet.',
      message: 'Professionelle beslag- og låseløsninger til byggeriet.',
      active: true,
      sortOrder: 2,
      featured: false,
    },
    {
      id: 'part-jorgen-kraemer-rasmussen',
      name: 'Jørgen Kræmer Rasmussen',
      companyName: 'Jørgen Kræmer Rasmussen',
      logo: '/partners/jorgen-kraemer-rasmussen.png',
      logoUrl: '/partners/jorgen-kraemer-rasmussen.png',
      category: 'AGF PLAY',
      sponsorCategory: 'AGF PLAY',
      websiteUrl: '',
      shortDescription: 'Erhvervspartner og mangeårig støtte af AGF Håndbold.',
      message: 'Erhvervspartner og mangeårig støtte af AGF Håndbold.',
      active: true,
      sortOrder: 3,
      featured: false,
    },
    {
      id: 'part-djurslands-bank',
      name: 'Djurslands Bank',
      companyName: 'Djurslands Bank',
      logo: '/partners/djurslands-bank.png',
      logoUrl: '/partners/djurslands-bank.png',
      category: 'AGF PLAY',
      sponsorCategory: 'AGF PLAY',
      websiteUrl: 'https://www.djurslandsbank.dk',
      shortDescription: 'Nærværende, handlekraftig og lokal bank i Aarhus og Østjylland.',
      message: 'Nærværende, handlekraftig og lokal bank i Aarhus og Østjylland.',
      active: true,
      sortOrder: 4,
      featured: false,
    },
    {
      id: 'part-harald-nyborg',
      name: 'Harald Nyborg',
      companyName: 'Harald Nyborg',
      logo: '/partners/harald-nyborg.png',
      logoUrl: '/partners/harald-nyborg.png',
      category: 'AGF PLAY',
      sponsorCategory: 'AGF PLAY',
      websiteUrl: 'https://www.harald-nyborg.dk',
      shortDescription: 'Altid lave priser til hus, have og fritid.',
      message: 'Altid lave priser til hus, have og fritid.',
      active: true,
      sortOrder: 5,
      featured: false,
    },
    {
      id: 'part-scorjobbet',
      name: 'Scorjobbet.dk',
      companyName: 'Scorjobbet.dk',
      logo: '/partners/scorjobbet.png',
      logoUrl: '/partners/scorjobbet.png',
      category: 'AGF PLAY',
      sponsorCategory: 'AGF PLAY',
      websiteUrl: 'https://scorjobbet.dk',
      shortDescription: 'Jobportal der matcher dygtige kandidater med ambitiøse virksomheder.',
      message: 'Jobportal der matcher dygtige kandidater med ambitiøse virksomheder.',
      active: true,
      sortOrder: 6,
      featured: false,
    },
    // 3. AGF MATCH
    {
      id: 'part-kaufmann',
      name: 'Kaufmann',
      companyName: 'Kaufmann',
      logo: '/partners/kaufmann.png',
      logoUrl: '/partners/kaufmann.png',
      category: 'AGF MATCH',
      sponsorCategory: 'AGF MATCH',
      websiteUrl: 'https://www.kaufmann.dk',
      shortDescription: 'Eksklusiv herremode og personlig service i Aarhus og resten af landet.',
      message: 'Eksklusiv herremode og personlig service i Aarhus og resten af landet.',
      active: true,
      sortOrder: 1,
      featured: false,
    },
    {
      id: 'part-v-steel',
      name: 'V Steel A/S',
      companyName: 'V Steel A/S',
      logo: '/partners/v-steel.png',
      logoUrl: '/partners/v-steel.png',
      category: 'AGF MATCH',
      sponsorCategory: 'AGF MATCH',
      websiteUrl: 'https://www.vsteel.dk',
      shortDescription: 'Professionel leverandør af stålkonstruktioner og montage.',
      message: 'Professionel leverandør af stålkonstruktioner og montage.',
      active: true,
      sortOrder: 2,
      featured: false,
    },
    // 4. AGF FORDEL
    {
      id: 'part-ak-smede',
      name: 'AK Smede & Pladebearbejdning',
      companyName: 'AK Smede & Pladebearbejdning',
      logo: '/partners/ak-smede.png',
      logoUrl: '/partners/ak-smede.png',
      category: 'AGF FORDEL',
      sponsorCategory: 'AGF FORDEL',
      websiteUrl: '',
      shortDescription: 'Specialister i specialfremstillet smedearbejde og pladebearbejdning.',
      message: 'Specialister i specialfremstillet smedearbejde og pladebearbejdning.',
      active: true,
      sortOrder: 1,
      featured: false,
    },
    {
      id: 'part-dansk-psykologisk-forlag',
      name: 'Dansk Psykologisk Forlag',
      companyName: 'Dansk Psykologisk Forlag',
      logo: '/partners/dansk-psykologisk-forlag.png',
      logoUrl: '/partners/dansk-psykologisk-forlag.png',
      category: 'AGF FORDEL',
      sponsorCategory: 'AGF FORDEL',
      websiteUrl: 'https://dpf.dk',
      shortDescription: 'Førende forlag inden for psykologisk og pædagogisk fagviden.',
      message: 'Førende forlag inden for psykologisk og pædagogisk fagviden.',
      active: true,
      sortOrder: 2,
      featured: false,
    },
    {
      id: 'part-ringkjobing-landbobank',
      name: 'Ringkjøbing Landbobank',
      companyName: 'Ringkjøbing Landbobank',
      logo: '/partners/ringkjobing-landbobank.png',
      logoUrl: '/partners/ringkjobing-landbobank.png',
      category: 'AGF FORDEL',
      sponsorCategory: 'AGF FORDEL',
      websiteUrl: 'https://www.landbobanken.dk',
      shortDescription: 'En af Danmarks mest solide banker med stærke kunderelationer.',
      message: 'En af Danmarks mest solide banker med stærke kunderelationer.',
      active: true,
      sortOrder: 3,
      featured: false,
    },
    {
      id: 'part-cafe-faust',
      name: 'Café Faust',
      companyName: 'Café Faust',
      logo: '/partners/cafe-faust.png',
      logoUrl: '/partners/cafe-faust.png',
      category: 'AGF FORDEL',
      sponsorCategory: 'AGF FORDEL',
      websiteUrl: 'https://cafefaust.dk',
      shortDescription: 'Hyggelig caféstemning og god mad lige ved Åen i Aarhus centrum.',
      message: 'Hyggelig caféstemning og god mad lige ved Åen i Aarhus centrum.',
      active: true,
      sortOrder: 4,
      featured: false,
    },
    {
      id: 'part-formueforvalterne',
      name: 'Formueforvalterne – Investering & Tryghed',
      companyName: 'Formueforvalterne – Investering & Tryghed',
      logo: '/partners/formueforvalterne.png',
      logoUrl: '/partners/formueforvalterne.png',
      category: 'AGF FORDEL',
      sponsorCategory: 'AGF FORDEL',
      websiteUrl: 'https://formueforvalterne.dk',
      shortDescription: 'Uafhængig formueforvaltning og rådgivning med fokus på tryghed.',
      message: 'Uafhængig formueforvaltning og rådgivning med fokus på tryghed.',
      active: true,
      sortOrder: 5,
      featured: false,
    },
    {
      id: 'part-lph-byg',
      name: 'LPH Byg',
      companyName: 'LPH Byg',
      logo: '/partners/lph-byg.png',
      logoUrl: '/partners/lph-byg.png',
      category: 'AGF FORDEL',
      sponsorCategory: 'AGF FORDEL',
      websiteUrl: 'https://lph-byg.dk',
      shortDescription: 'Kvalitetsbyggeri og renovering med stolte håndværkstraditioner.',
      message: 'Kvalitetsbyggeri og renovering med stolte håndværkstraditioner.',
      active: true,
      sortOrder: 6,
      featured: false,
    },
    {
      id: 'part-ph-trading',
      name: 'PH Trading',
      companyName: 'PH Trading',
      logo: '/partners/ph-trading.png',
      logoUrl: '/partners/ph-trading.png',
      category: 'AGF FORDEL',
      sponsorCategory: 'AGF FORDEL',
      websiteUrl: 'https://www.phtrading.dk',
      shortDescription: 'Pålidelig handelspartner inden for distribution og leverancer.',
      message: 'Pålidelig handelspartner inden for distribution og leverancer.',
      active: true,
      sortOrder: 7,
      featured: false,
    },
    // 5. ØVRIGE MATCHDAY-PARTNERE
    {
      id: 'part-looad',
      name: 'Looad',
      companyName: 'Looad',
      logo: '/partners/looad.png',
      logoUrl: '/partners/looad.png',
      category: 'ØVRIGE MATCHDAY-PARTNERE',
      sponsorCategory: 'ØVRIGE MATCHDAY-PARTNERE',
      websiteUrl: 'https://looad.dk/pages/klub-agf-haandbold',
      shortDescription: 'Officiel energipartner. Skift elselskab til Looad og støt samtidig AGF Håndbold.',
      message: 'Officiel energipartner. Skift elselskab til Looad og støt samtidig AGF Håndbold.',
      offer: 'Støt klubben ved at vælge grøn strøm fra Looad.',
      optionalMatchdayOffer: 'Støt klubben ved at vælge grøn strøm fra Looad.',
      active: true,
      sortOrder: 1,
      featured: false,
      attachedTo: 'tilmelding',
    },
  ],
  announcements: [
    {
      id: 'ann-1',
      matchdayId: 'matchday-1',
      title: '🎯 Skudmåleren er åben i fanzonen!',
      message: 'Test din skudhastighed i pausen. Mikkel Lind fører lige nu med 96 km/t!',
      priority: 'important',
      active: true,
      createdAt: '12:30',
    },
    {
      id: 'ann-2',
      matchdayId: 'matchday-1',
      title: '🍺 Pausetilbud aktivt nu',
      message: 'Få 2 fadøl for 80 kr. i alle arenaens kiosker – find kuponen under Tilbud.',
      priority: 'normal',
      active: true,
      createdAt: '12:45',
    }
  ],
  staffUsers: [
    {
      id: 'staff-admin-1',
      name: 'AGF Matchday Admin',
      pin: '1880',
      role: 'ADMIN',
      createdAt: '2026-09-01T10:00:00.000Z',
    },
    {
      id: 'staff-kiosk-1',
      name: 'Kioskvagt Hal A (Lars)',
      pin: '1902',
      role: 'STAFF',
      createdAt: '2026-09-01T10:00:00.000Z',
    },
    {
      id: 'staff-kiosk-2',
      name: 'Kioskvagt Hal B (Mette)',
      pin: '2026',
      role: 'STAFF',
      createdAt: '2026-09-01T10:00:00.000Z',
    }
  ],
  redemptionLogs: [],
  canonicalAppUrl: ''
};
