import { MatchdayDatabase } from './types.ts';

export const initialDatabase: MatchdayDatabase = {
  adminPin: '1880', // Foundation year of AGF
  visits: 142,
  activeMatchdayId: 'matchday-1',
  matchdays: [
    {
      id: 'matchday-1',
      title: 'AGF Matchday – Dobbeltbrag i Ceres Arena',
      date: 'Lørdag d. 10. oktober 2026',
      venue: 'Ceres Arena, Hal 1',
      active: true,
      featuredHero: {
        enabled: true,
        badge: 'LIVE NU',
        title: 'STEM PÅ KAMPENS SPILLER',
        subtitle: 'Afstemningen til damekampen er åben netop nu!',
        actionText: 'AFGIV DIN STEMME',
        actionTarget: 'stem',
      },
      looadUrl: 'https://looad.dk/event/agf-matchday-2026',
      looadTitle: 'Tilmeld dig pauselodtrækningen og fanzonen',
      looadDescription: 'Tilmeld dig via Looad herunder og deltag i dagens præmielodtrækning fra AGF og vores partnere.',
      welcomeMessage: 'Velkommen til AGF Håndbold i Ceres Arena. Støt de hvide!',
      createdAt: new Date().toISOString(),
    },
    {
      id: 'matchday-2',
      title: 'AGF Håndbold – Lokalderby mod Skanderborg',
      date: 'Søndag d. 25. oktober 2026',
      venue: 'Ceres Arena, Hal 1',
      active: false,
      featuredHero: {
        enabled: true,
        badge: 'KOMMENDE',
        title: 'VELKOMMEN TIL DERBY',
        subtitle: 'Dørene åbner kl. 13:00 til sæsonens største lokalopgør',
        actionText: 'SE PROGRAMMET',
        actionTarget: 'program',
      },
      looadUrl: 'https://looad.dk/event/agf-matchday-2026',
      looadTitle: 'Tilmeld dig fanzonen',
      looadDescription: 'Tilmeld dig her og vær med på dagen.',
      welcomeMessage: 'Gør dig klar til det store lokalopgør!',
      createdAt: new Date().toISOString(),
    }
  ],
  matches: [
    {
      id: 'match-1',
      matchdayId: 'matchday-1',
      category: 'DAMER',
      league: '1. Division Damer',
      homeTeam: 'AGF Håndbold',
      awayTeam: 'Horsens HK',
      time: '12:45',
      status: 'live',
      homeScore: 16,
      awayScore: 14,
      partner: 'Arbejdernes Landsbank',
    },
    {
      id: 'match-2',
      matchdayId: 'matchday-1',
      category: 'HERRER',
      league: '1. Division Herrer',
      homeTeam: 'AGF Håndbold',
      awayTeam: 'Skanderborg AGF',
      time: '15:15',
      status: 'upcoming',
      homeScore: 0,
      awayScore: 0,
      partner: 'Ceres Bryggerierne',
    }
  ],
  schedule: [
    {
      id: 'sched-1',
      matchdayId: 'matchday-1',
      time: '11:45',
      title: 'Dørene åbner & Fanzonen starter',
      description: 'Kiosken tænder grillen, og der er musik samt opvarmningsaktiviteter i hallen.',
      location: 'Ceres Arena - Fanzone & Hal 1',
      icon: 'door-open',
      status: 'completed',
      order: 1,
    },
    {
      id: 'sched-2',
      matchdayId: 'matchday-1',
      time: '12:45',
      title: 'AGF Damer vs. Horsens HK',
      description: '1. Division Damer. Støt pigerne i jagten på to vigtige point!',
      location: 'Bane 1',
      icon: 'trophy',
      status: 'live',
      order: 2,
    },
    {
      id: 'sched-3',
      matchdayId: 'matchday-1',
      time: '14:20',
      title: 'Pauseaktivitet: Skudmåler & Konkurrencer',
      description: 'Test dit skud på vores radar i fanzonen eller vind præmier fra Looad.',
      location: 'Fanzonen bag sektion B',
      icon: 'target',
      status: 'upcoming',
      order: 3,
    },
    {
      id: 'sched-4',
      matchdayId: 'matchday-1',
      time: '15:15',
      title: 'AGF Herrer vs. Skanderborg AGF',
      description: 'Det store lokalopgør! Fuld tænding på lægterne.',
      location: 'Bane 1',
      icon: 'swords',
      status: 'upcoming',
      order: 4,
    },
    {
      id: 'sched-5',
      matchdayId: 'matchday-1',
      time: '17:00',
      title: 'Kåring af Kampens Spiller & Aftermatch',
      description: 'Præmieoverrækkelse præsenteret af Arbejdernes Landsbank.',
      location: 'Midtercirklen',
      icon: 'award',
      status: 'upcoming',
      order: 5,
    }
  ],
  products: [
    {
      id: 'prod-1',
      name: 'Fadøl (Royal Pilsner / Classic 0,5L)',
      category: 'Fadøl',
      price: 45,
      available: true,
      promotionalLabel: 'Favorit',
      description: 'Frisktappet kold fadøl fra Ceres.',
    },
    {
      id: 'prod-2',
      name: 'Pausepakke (2 store Fadøl)',
      category: 'Fadøl',
      price: 80,
      available: true,
      promotionalLabel: 'Spar 10 kr',
      description: 'Tag en ven med i baren og spar penge.',
    },
    {
      id: 'prod-3',
      name: 'Faxe Kondi / Pepsi Max (0,5L)',
      category: 'Sodavand',
      price: 25,
      available: true,
      promotionalLabel: '',
      description: 'Iskold sodavand.',
    },
    {
      id: 'prod-4',
      name: 'Kildevand (0,5L)',
      category: 'Vand',
      price: 20,
      available: true,
      promotionalLabel: '',
      description: 'Naturligt mineralvand.',
    },
    {
      id: 'prod-5',
      name: 'Filterkaffe (Friskbrygget)',
      category: 'Kaffe',
      price: 20,
      available: true,
      promotionalLabel: '',
      description: 'Varm sort kaffe fra baren.',
    },
    {
      id: 'prod-6',
      name: 'Varm Kakao m/ flødeskum',
      category: 'Kaffe',
      price: 25,
      available: true,
      promotionalLabel: '',
      description: 'Perfekt til de kolde dage.',
    },
    {
      id: 'prod-7',
      name: 'Fransk Hotdog',
      category: 'Mad',
      price: 35,
      available: true,
      promotionalLabel: 'Populær',
      description: 'Sprødt baguettebrød med klassisk fransk dressing.',
    },
    {
      id: 'prod-8',
      name: 'Toast m/ skinke og ost',
      category: 'Mad',
      price: 35,
      available: true,
      promotionalLabel: '',
      description: 'Lunt og nystegt toast.',
    },
    {
      id: 'prod-9',
      name: 'Pølsehorn',
      category: 'Mad',
      price: 25,
      available: true,
      promotionalLabel: '',
      description: 'Lækkert mellemmåltid til børn og voksne.',
    },
    {
      id: 'prod-10',
      name: 'Popcorn (Stor bøtte)',
      category: 'Snacks',
      price: 30,
      available: true,
      promotionalLabel: '',
      description: 'Varme, saltede popcorn.',
    },
    {
      id: 'prod-11',
      name: 'Saltede Peanuts',
      category: 'Snacks',
      price: 20,
      available: false, // Out of stock example
      promotionalLabel: '',
      description: 'Klassiske peanuts til øllen.',
    },
    {
      id: 'prod-12',
      name: 'Haribo pose (Matador Mix / Stjernemix)',
      category: 'Slik',
      price: 25,
      available: true,
      promotionalLabel: '',
      description: '120g blandet slik.',
    }
  ],
  coupons: [
    {
      id: 'coup-1',
      matchdayId: 'matchday-1',
      title: '🔥 PAUSETILBUD – 2 fadøl for 80 kr.',
      description: 'Køb 2 fadøl i pausen og spar 10 kr. Aktivér kuponen og vis den i kiosken inden for 10 minutter.',
      originalPrice: 90,
      offerPrice: 80,
      active: true,
      activationDurationMinutes: 10,
      maxRedemptions: 150,
      redemptionsCount: 38,
      sponsor: 'Ceres Bryggerierne',
    },
    {
      id: 'coup-2',
      matchdayId: 'matchday-1',
      title: '🌭 Matchday Menu: Fransk hotdog + Sodavand',
      description: 'Vælg en valgfri sodavand og en fransk hotdog for kun 50 kr. (normalpris 60 kr.).',
      originalPrice: 60,
      offerPrice: 50,
      active: true,
      activationDurationMinutes: 15,
      maxRedemptions: 100,
      redemptionsCount: 24,
      sponsor: 'Arbejdernes Landsbank',
    },
    {
      id: 'coup-3',
      matchdayId: 'matchday-1',
      title: '☕ Kaffe & Kage tilbud',
      description: 'Få en kop friskbrygget kaffe og et stykke chokoladekage for 30 kr.',
      originalPrice: 45,
      offerPrice: 30,
      active: true,
      activationDurationMinutes: 15,
      maxRedemptions: 80,
      redemptionsCount: 19,
      sponsor: 'Kiosken',
    }
  ],
  couponRedemptions: [],
  competitions: [
    {
      id: 'comp-1',
      name: 'Skudmåler',
      description: 'Hvem har kampens hårdeste skudarm? Mål dit håndboldskud i km/t på radaren i fanzonen.',
      scoringUnit: 'km/t',
      higherScoreWins: true,
      active: true,
      maxLeaderboardEntries: 5,
      sponsor: 'hummel',
    },
    {
      id: 'comp-2',
      name: 'Præcisionsskydning',
      description: 'Ram plet i målhjørnerne og saml flest mulige point på 3 forsøg.',
      scoringUnit: 'point',
      higherScoreWins: true,
      active: true,
      maxLeaderboardEntries: 5,
      sponsor: 'Looad',
    },
    {
      id: 'comp-3',
      name: 'Crossbar Challenge',
      description: 'Hvor mange gange i træk kan du ramme overliggeren fra 7-meter stregen?',
      scoringUnit: 'træffere',
      higherScoreWins: true,
      active: true,
      maxLeaderboardEntries: 5,
      sponsor: 'Arbejdernes Landsbank',
    }
  ],
  scores: [
    // Skudmåler scores
    { id: 'score-1', competitionId: 'comp-1', matchdayId: 'matchday-1', participantName: 'Mikkel Lind', score: 96, timestamp: '12:15', isNewRecord: true },
    { id: 'score-2', competitionId: 'comp-1', matchdayId: 'matchday-1', participantName: 'Frederik B.', score: 92, timestamp: '12:20', isNewRecord: false },
    { id: 'score-3', competitionId: 'comp-1', matchdayId: 'matchday-1', participantName: 'Alma V.', score: 87, timestamp: '12:28', isNewRecord: false },
    { id: 'score-4', competitionId: 'comp-1', matchdayId: 'matchday-1', participantName: 'Oscar K.', score: 84, timestamp: '12:35', isNewRecord: false },
    { id: 'score-5', competitionId: 'comp-1', matchdayId: 'matchday-1', participantName: 'Laura Schmidt', score: 81, timestamp: '12:40', isNewRecord: false },
    
    // Præcisionsskydning scores
    { id: 'score-6', competitionId: 'comp-2', matchdayId: 'matchday-1', participantName: 'Jonas Dahl', score: 28, timestamp: '12:10', isNewRecord: true },
    { id: 'score-7', competitionId: 'comp-2', matchdayId: 'matchday-1', participantName: 'Sofie M.', score: 24, timestamp: '12:18', isNewRecord: false },
    { id: 'score-8', competitionId: 'comp-2', matchdayId: 'matchday-1', participantName: 'Rasmus P.', score: 20, timestamp: '12:25', isNewRecord: false },

    // Crossbar Challenge scores
    { id: 'score-9', competitionId: 'comp-3', matchdayId: 'matchday-1', participantName: 'Emil Thorn', score: 4, timestamp: '12:30', isNewRecord: true },
    { id: 'score-10', competitionId: 'comp-3', matchdayId: 'matchday-1', participantName: 'Mathias H.', score: 3, timestamp: '12:32', isNewRecord: false }
  ],
  votingSessions: [
    {
      id: 'vote-damer',
      matchdayId: 'matchday-1',
      category: 'DAMER',
      title: 'Kampens Spiller – Damer (AGF vs. Horsens HK)',
      status: 'open',
      sponsor: 'Arbejdernes Landsbank',
      publicResultsEnabled: false,
    },
    {
      id: 'vote-herrer',
      matchdayId: 'matchday-1',
      category: 'HERRER',
      title: 'Kampens Spiller – Herrer (AGF vs. Skanderborg AGF)',
      status: 'pending',
      sponsor: 'Ceres Bryggerierne',
      publicResultsEnabled: false,
    }
  ],
  players: [
    // Damer spillere
    { id: 'p-1', sessionId: 'vote-damer', name: 'Laura Nielsen', number: 1, position: 'Målvogter' },
    { id: 'p-2', sessionId: 'vote-damer', name: 'Sofie Møller', number: 7, position: 'Playmaker' },
    { id: 'p-3', sessionId: 'vote-damer', name: 'Emma Jensen', number: 10, position: 'Venstre Fløj' },
    { id: 'p-4', sessionId: 'vote-damer', name: 'Mathilde Holm', number: 14, position: 'Stregspiller' },
    { id: 'p-5', sessionId: 'vote-damer', name: 'Julie Kristensen', number: 22, position: 'Højre Back' },
    { id: 'p-6', sessionId: 'vote-damer', name: 'Amalie Winther', number: 18, position: 'Forsvarsgeneral' },

    // Herrer spillere
    { id: 'p-7', sessionId: 'vote-herrer', name: 'Mikkel Rasmussen', number: 1, position: 'Målvogter' },
    { id: 'p-8', sessionId: 'vote-herrer', name: 'Frederik Bruun', number: 4, position: 'Playmaker' },
    { id: 'p-9', sessionId: 'vote-herrer', name: 'Mads Svendsen', number: 9, position: 'Stregspiller' },
    { id: 'p-10', sessionId: 'vote-herrer', name: 'Christian Lind', number: 15, position: 'Venstre Back' },
    { id: 'p-11', sessionId: 'vote-herrer', name: 'Magnus Toft', number: 21, position: 'Højre Fløj' },
    { id: 'p-12', sessionId: 'vote-herrer', name: 'Kasper Broe', number: 11, position: 'Højre Back' }
  ],
  votes: [
    { id: 'v-1', sessionId: 'vote-damer', playerId: 'p-2', deviceId: 'dev-seed-1', timestamp: '12:50' },
    { id: 'v-2', sessionId: 'vote-damer', playerId: 'p-2', deviceId: 'dev-seed-2', timestamp: '12:52' },
    { id: 'v-3', sessionId: 'vote-damer', playerId: 'p-1', deviceId: 'dev-seed-3', timestamp: '12:55' },
    { id: 'v-4', sessionId: 'vote-damer', playerId: 'p-4', deviceId: 'dev-seed-4', timestamp: '13:00' },
    { id: 'v-5', sessionId: 'vote-damer', playerId: 'p-2', deviceId: 'dev-seed-5', timestamp: '13:05' },
  ],
  partners: [
    {
      id: 'part-1',
      name: 'Ceres Bryggerierne',
      logo: '/agf-logo.svg',
      websiteUrl: 'https://royalunibrew.dk',
      message: 'Stolt hovedpartner og leverandør af forfriskninger til AGF Håndbold.',
      category: 'Hovedpartner',
      offer: 'Prøv dagens Matchday Fadøl i Ceres Arena.',
      active: true,
      attachedTo: 'kiosk',
    },
    {
      id: 'part-2',
      name: 'Arbejdernes Landsbank',
      logo: '/agf-logo.svg',
      websiteUrl: 'https://al-bank.dk',
      message: 'Danmarks mest anbefalede bank – officiel sponsor af Kampens Spiller.',
      category: 'Matchday Partner',
      offer: 'Stem på Kampens Spiller og vind VIP-billetter.',
      active: true,
      attachedTo: 'kampens-spiller',
    },
    {
      id: 'part-3',
      name: 'hummel',
      logo: '/agf-logo.svg',
      websiteUrl: 'https://hummel.dk',
      message: 'Stolt tøjsponsor for AGF. Karma og passion på banen.',
      category: 'Tøjpartner',
      offer: 'Få 20% rabat på AGF-trøjer med koden AGF1880.',
      active: true,
      attachedTo: 'comp-1',
    },
    {
      id: 'part-4',
      name: 'Looad',
      logo: '/agf-logo.svg',
      websiteUrl: 'https://looad.dk',
      message: 'Intelligente lade- og arrangementsløsninger. Partner på dagens tilmelding.',
      category: 'Aktivitetspartner',
      offer: 'Tilmeld dig dagens lodtrækning i tilmeldingsfanen.',
      active: true,
      attachedTo: 'tilmelding',
    },
    {
      id: 'part-5',
      name: 'AGF Fanclub Aarhus',
      logo: '/agf-logo.svg',
      websiteUrl: 'https://agf-fanclub.dk',
      message: 'Vi skaber stemningen i Ceres Arena. Vær med i fællesskabet!',
      category: 'Fællesskabspartner',
      active: true,
    }
  ],
  announcements: [
    {
      id: 'ann-1',
      matchdayId: 'matchday-1',
      title: '🎯 Skudmåleren er åben i fanzonen!',
      message: 'Test din skudhastighed i pausen. Mikkel Lind fører lige nu med 96 km/t!',
      priority: 'important',
      active: true,
      createdAt: '12:30',
    },
    {
      id: 'ann-2',
      matchdayId: 'matchday-1',
      title: '🍺 Pausetilbud aktivt nu',
      message: 'Få 2 fadøl for 80 kr. i alle arenaens kiosker – find kuponen under Tilbud.',
      priority: 'normal',
      active: true,
      createdAt: '12:45',
    }
  ],
  staffUsers: [
    {
      id: 'staff-admin-1',
      name: 'AGF Matchday Admin',
      pin: '1880',
      role: 'ADMIN',
      createdAt: '2026-09-01T10:00:00.000Z',
    },
    {
      id: 'staff-kiosk-1',
      name: 'Kioskvagt Hal A (Lars)',
      pin: '1902',
      role: 'STAFF',
      createdAt: '2026-09-01T10:00:00.000Z',
    },
    {
      id: 'staff-kiosk-2',
      name: 'Kioskvagt Hal B (Mette)',
      pin: '2026',
      role: 'STAFF',
      createdAt: '2026-09-01T10:00:00.000Z',
    }
  ],
  redemptionLogs: [],
  canonicalAppUrl: ''
};
